### ISSUE TITLE
Please provide AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [mysteriumnetwork/mysterium-vpn#263]
Please provide an AppImage for Linux, thank you.

**Comment by shroomist** [comment]
hello @probonopd, thanks fo your feedback showing interest in AppImage package.
Currently we're focusing on getting Windows distribution somewhat stable.
In earlier project stages we've tested and I could confirm that AppImage builds are possible and should be not too complicated to accomplish. Unfortunately GUI for Linux it's not currently on top of our priority list.

meanwhile you are welcome to try our CLI client from [core](https://github.com/MysteriumNetwork/node/releases)

**Comment by probonopd** [comment]
Thanks for the update @shroomist. No hurries. Please ping me once there is a Linux version. Thanks.

**Comment by asddsaz** [comment]
+1

**Comment by asddsaz** [comment]
@shroomist Is there any ETA on when Linux will be supported?

**Comment by probonopd** [comment]
This was closed but there is no Linux version on https://github.com/mysteriumnetwork/mysterium-vpn/releases. Does this mean Linux will not be supported @ignasbernotas? Thanks.
