### ISSUE TITLE
Mysterion cannot get the latest nodes information

### ISSUE THREAD

**Issue by tonyxia2016** [mysteriumnetwork/mysterium-vpn#273]
Mysterion cannot get the latest nodes info. All my mysterion (Winodws 7, Windows 10 and Mac OS X) always show some old nodes information. It is different with the nodes listed in  https://testnet.mysterium.network

**Comment by hust283** [comment]
Looks like this issue is gone in the latest version.

**Comment by tonyxia2016** [comment]
Looks fixed in the latest version.
