### ISSUE TITLE
Windows VPN client not bypassing restrictions

### ISSUE THREAD

**Issue by serejandmyself** [mysteriumnetwork/mysterium-vpn#361]
Testing the UI alpha windows version. I am not managing to connect to most addresses, however, managed Finland and France. In both cases after the connection I am not managing to bypass local restrictions, so it isn't working as I understand. 

Any known issues? 

(Testing from the .ru zone)

**Comment by serejandmyself** [comment]
UPD. Same problems for the new version 0.6

**Comment by donce** [comment]
Does your IP change after your successful connection? If so, then those nodes that you are connecting to might have the same restrictions you're trying to avoid - I would suggest trying other nodes.

**Comment by serejandmyself** [comment]
Is there a way to filter "dead" nodes?

**Comment by donce** [comment]
There is an ability to see node quality in Android app - we're planning to add this functionality in following weeks for Desktop as well.

**Comment by donce** [comment]
https://github.com/mysteriumnetwork/mysterium-vpn/issues/387

**Comment by serejandmyself** [comment]
Ok, great. Thanks for the answers. So maybe this can be closed for now
