### ISSUE TITLE
As a user I want to run a service

### ISSUE THREAD

**Issue by ignasbernotas** [mysteriumnetwork/mysterium-vpn#406]
Subtasks:
- [x] Create separate Provider page in desktop app (@ignasbernotas) 
- [x] Show service status in Provider page
- [x] Start service in from Provider page
- [x] Stop service in from Provider page
- [x] Provider status pulling in Desktop App (may want to think about Websockets*) @donce 
- [x] Fetch services list - if service is already running, show it as running and allow stopping it
- [x] Build Mysterium VPN, send to Andrius, Mindaugas and Germantas to test it
- [x] Quiting application stops service
- [x] Show error when service starting fails
- [x] Fix other TODOs in code, which are important
- [x] Loading visual image status handling (@ignasbernotas can you clarify this one?)
 
As a user I want to run a service

AC:
* I need to be able to open service runner page
* I need to see service status
* I need to be able to start WG service
* I need to be able to stop WG service
* For now only WG is required

**Comment by Waldz** [comment]
I started to do https://github.com/mysteriumnetwork/js-tequilapi/issues/30

**Comment by donce** [comment]
PR in mysterium-vpn-js (finished):
https://github.com/mysteriumnetwork/mysterium-vpn-js/pull/4
PR in mysterium-vpn (WIP):
https://github.com/mysteriumnetwork/mysterium-vpn/pull/446

Updated task description with what is left to do. It's important to make a custom build to start testing it out - most of the remaining parts are not critical, and teammates can start testing it in parallel.
