### ISSUE TITLE
App shows error on service start button click if service is already running

### ISSUE THREAD

**Issue by mjankauskas** [mysteriumnetwork/mysterium-vpn#448]
MacOS app versio 0.8.0

When Service is running in background (Quitting app or killing it)
When next time app is ran and user tries to start service it shows an error.

Expected:

On app start it check if service is running in background and if is true fetches all parameters needed to show UI in synced state.

If not possible now quick hack would be On service start CTA click 1. check if service is running. 2. Stop it 3. Start service and continue as expected

**Comment by ignasbernotas** [comment]
This is fixed with the modal navigation release @mjankauskas
