### ISSUE TITLE
yarn download:bins:osx throws an error of missing command download-mysterium-client

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/mysterium-vpn#475]
on macos:

yarn download:bins:osx
error Command "download-mysterium-client" not found.

**Comment by donce** [comment]
Tested it - seems to work fine for me. Have you done any custom actions before? Are you using latest `master`?

**Comment by tadaskay** [comment]
You should execute `yarn download:bins:osx` in project directory (where `package.json` is located)

**Comment by cvl** [comment]
Started working after computer restart. Thanks.
